name: Deploy info.goldenwin.vn (static)

on:
  push:
    branches: [ main ]
    paths:
      - '**'                                  # theo dõi mọi thay đổi (hoặc liệt kê cụ thể nếu muốn)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare target dir
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_INFO }}
          username: ${{ secrets.SSH_USER_INFO }}
          key: ${{ secrets.SSH_PRIVATE_KEY_INFO }}
          script: |
            mkdir -p /home/goldenwin-info/htdocs/info.goldenwin.vn
            rm -rf /home/goldenwin-info/htdocs/info.goldenwin.vn/*

      - name: Upload static files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST_INFO }}
          username: ${{ secrets.SSH_USER_INFO }}
          key: ${{ secrets.SSH_PRIVATE_KEY_INFO }}
          source: "./**"                       # lấy toàn bộ nội dung repo
          target: "/home/goldenwin-info/htdocs/info.goldenwin.vn"
          strip_components: 0
          overwrite: true
          dotfiles: true

      - name: Remove CI folder (optional)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_INFO }}
          username: ${{ secrets.SSH_USER_INFO }}
          key: ${{ secrets.SSH_PRIVATE_KEY_INFO }}
          script: |
            rm -rf /home/goldenwin-info/htdocs/info.goldenwin.vn/.github

      - name: Fix permissions (dirs 755, files 644)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_INFO }}
          username: ${{ secrets.SSH_USER_INFO }}
          key: ${{ secrets.SSH_PRIVATE_KEY_INFO }}
          script: |
            cd /home/goldenwin-info/htdocs/info.goldenwin.vn
            find . -type d -exec chmod 755 {} \;
            find . -type f -exec chmod 644 {} \;
